% Auto-generated by cameraCalibrator app on 11-Feb-2026
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/MATLAB Drive/newPor/4bb2c375-3765-4914-9b1e-56a7b2c57def.JPG',...
    '/MATLAB Drive/newPor/5a528e2c-4215-430f-9610-7fb25f91f72f.JPG',...
    '/MATLAB Drive/newPor/6ffc8b09-8d13-41ab-8f5a-4a014b60ea38.JPG',...
    '/MATLAB Drive/newPor/9f8ab8a6-28de-4df2-95b8-ac896bc1b54d.JPG',...
    '/MATLAB Drive/newPor/24e48bac-9a62-4776-851e-38c774c45941.JPG',...
    '/MATLAB Drive/newPor/54bcfea2-ab69-4f97-8504-adc4bfde15cf.JPG',...
    '/MATLAB Drive/newPor/92d70780-7649-4c7b-a5d3-1bce58da69fe.JPG',...
    '/MATLAB Drive/newPor/183bb106-75d8-44be-a343-80e4dbdde543.JPG',...
    '/MATLAB Drive/newPor/322aafe8-f57f-4528-8162-bdca2f4a1139.JPG',...
    '/MATLAB Drive/newPor/1142b33a-07e0-4e74-88fe-a88562888631.JPG',...
    '/MATLAB Drive/newPor/26369ffe-d5dd-431a-a432-e3abb87ff0a6.JPG',...
    '/MATLAB Drive/newPor/873876ff-d926-4d3b-a367-83eb1311facc.JPG',...
    '/MATLAB Drive/newPor/cbaa8552-eb3b-487b-85f0-c8cf3add5751.JPG',...
    '/MATLAB Drive/newPor/d8ac0708-4d8c-406e-81c9-0b0754ce79b0.JPG',...
    '/MATLAB Drive/newPor/d027773e-1938-4186-89ef-e4e4d2683fb7.JPG',...
    '/MATLAB Drive/newPor/ff41ca64-52f2-4799-823d-283d3c9bee06.JPG',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
minCornerMetric = 0.150000;
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'MinCornerMetric', minCornerMetric);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 13.000000;  % in millimeters
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')

% Save the main calibration parameters
save('phoneCalibration.mat', 'cameraParams');

% Also save intrinsics separately for easy access
intrinsics = cameraParams.Intrinsics;
save('cameraIntrinsics.mat', 'intrinsics');

% Export key parameters to a text file for reference
fid = fopen('calibration_summary.txt', 'w');
fprintf(fid, 'Phone Camera Calibration Summary\n');
fprintf(fid, '================================\n\n');
fprintf(fid, 'Image Size: %d x %d pixels\n', intrinsics.ImageSize(1), intrinsics.ImageSize(2));
fprintf(fid, 'Focal Length (fx, fy): %.4f, %.4f pixels\n', intrinsics.FocalLength(1), intrinsics.FocalLength(2));
fprintf(fid, 'Principal Point (cx, cy): %.4f, %.4f pixels\n', intrinsics.PrincipalPoint(1), intrinsics.PrincipalPoint(2));
fprintf(fid, 'Radial Distortion (k1, k2): %.6f, %.6f\n', intrinsics.RadialDistortion(1), intrinsics.RadialDistortion(2));
fprintf(fid, 'Mean Reprojection Error: %.4f pixels\n', cameraParams.MeanReprojectionError);
fprintf(fid, 'Number of Calibration Images: %d\n', cameraParams.NumPatterns);
fclose(fid);

% Export the intrinsic matrix (useful for other software)
K = intrinsics.K;
save('intrinsic_matrix.txt', 'K', '-ascii');

disp('All calibration files saved!');